# Generated by Django 4.1.5 on 2023-01-26 23:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6d551588-2441-4a2b-9119-64899614c1ac'), editable=False, primary_key=True, serialize=False),
        ),
    ]
