# Generated by Django 4.1.5 on 2023-01-27 00:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ef04c2f1-4e0b-4d86-bb8f-3da151ec07fd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
